apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: knr-test-image-pull
 namespace: default
spec:
 replicas: 1
 serviceName: knr-image-pull
 selector:
  matchLabels:
   app: knr-image-pull
 template:
  metadata:
   labels:
    app: knr-image-pull
  spec:
   containers:
   - name: knr-image-pull
    image: dev0-artifacts-registry.cn-shanghai.cr.aliyuncs.com/stargate/sfci/falcon-ali/kube-node-recycler-ali/test_docker_build:jenkins-falcon-ali-kube-node-recycler-ali-PR-8-1-itest
    ports:
    - containerPort: 80


kst-shh62f477f9avkfvdavlv


apiVersion: v1
data:
  pod-eviction-config.yaml: |-
    items:
{{ toYaml [] | indent 4 }}
kind: ConfigMap
metadata:
  labels: 
    app.kubernetes.io/name: kube-node-recycler
    app.kubernetes.io/part-of: clustermanagement
  name: kube-node-recycler
  namespace: default

kubectl get nodes --show-labels|awk -F" " {'print $6'}|awk -F"," {'print $17'}|sort -u
